export enum EventTypeKey {
  SYSTEM_RESET,
  SYSTEM_RESET_FAILED,
  SYSTEM_RESET_SUCCESS,
  SYSTEM_TEST_EVENT,

  WORKER_CREATE,
  WORKER_CREATE_FAILED,
  WORKER_CREATED,

  WORKER_UPDATE,
  WORKER_UPDATED,

  WORKER_START,
  WORKER_STARTED,

  WORKER_TERMINATE,
  WORKER_TERMINATED,

  WORKER_DELETE,
  WORKER_DELETED,

  WORKER_IMAGE_CREATE,
  WORKER_IMAGE_CREATE_FAILED,
  WORKER_IMAGE_CREATED,

  ZONE_CREATE,
  ZONE_CREATED,

  ZONE_DELETE,
  ZONE_DELETED,

  NODE_ASSIGN_WORKER,
  NODE_ASSIGNED_WORKER,

  NODE_UNASSIGN_WORKER,
  NODE_UNASSIGNED_WORKER,

  NODE_CREATE_FIBER,
  NODE_CREATE_FIBER_FAILED,
  NODE_FIBER_CREATED,

  NODE_UPDATE_FIBER,
  NODE_UPDATE_FIBER_FAILED,
  NODE_FIBER_UPDATED,

  NODE_DELETE_FIBER,
  NODE_DELETE_FIBER_FAILED,
  NODE_FIBER_DELETED,

  PORTAL_CREATE,
  PORTAL_CREATE_FAILED,
  PORTAL_CREATED,

  PORTAL_UPDATE,
  PORTAL_UPDATE_FAILED,
  PORTAL_UPDATED,

  PORTAL_SYNC,
  PORTAL_SYNC_FAILED,
  PORTAL_SYNCED,

  PORTAL_DELETE,
  PORTAL_DELETE_FAILED,
  PORTAL_DELETED,

  TRANSPONDER_CREATE,
  TRANSPONDER_CREATE_FAILED,
  TRANSPONDER_CREATED,

  TRANSPONDER_UPDATE,
  TRANSPONDER_UPDATE_FAILED,
  TRANSPONDER_UPDATED,

  TRANSPONDER_DELETE,
  TRANSPONDER_DELETE_FAILED,
  TRANSPONDER_DELETED,
}