-- AlterEnum
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_CREATE';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_CREATE_FAILED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_CREATED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_ATTACH';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_ATTACH_FAILED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_ATTACHED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_DETACH';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_DETACH_FAILED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_DETACHED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_DELETE';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_DELETE_FAILED';
ALTER TYPE "EventType" ADD VALUE 'WORKER_DISK_DELETED';

-- AlterTable
ALTER TABLE "WorkerDisk"
    ADD COLUMN "status" "ResourceStatus" NOT NULL DEFAULT 'QUEUED',
    ADD COLUMN "deviceTarget" TEXT,
    ALTER COLUMN "hostPath" DROP NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "WorkerDisk_workerId_deviceTarget_key"
    ON "WorkerDisk"("workerId", "deviceTarget");
