ALTER TABLE "AtomVolume" ALTER COLUMN "mountPoint" DROP NOT NULL;

UPDATE "AtomVolume" SET "mountPoint" = NULL WHERE "atomId" IS NULL;

ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ATOM_VOLUME_RESIZE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ATOM_VOLUME_RESIZE_FAILED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ATOM_VOLUME_RESIZED';
