import "./globals.css";
import "@/libs/extensions/array-extension";
import "@/libs/extensions/string-extension";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppBar } from "@/core/ui/AppBar";
import { Footer } from "@/core/ui/Footer";
import { TickProvider } from "@/auth/ui/TickProvider";
import { DialogProvider } from "@/core/ui/DialogProvider";

import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log((await cookies()).toString());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid min-h-dvh grid-rows-[64px_1fr_auto]`}
      >
        <TickProvider>
          <DialogProvider>
            <AppBar />
            {children}
            <Footer />
          </DialogProvider>
        </TickProvider>
      </body>
    </html>
  );
}
