import "./globals.css";
import "@/libs/extensions/array-extension";
import "@/libs/extensions/string-extension";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppBar } from "@/core/ui/AppBar";
import { Footer } from "@/core/ui/Footer";
import { TickProvider } from "@/auth/ui/TickProvider";
import { WebSocketProvider } from "@/core/ui/WebsocketProvider";
import { DialogProvider } from "@/core/ui/DialogProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid min-h-dvh grid-rows-[64px_1fr_auto]`}
      >
        <TickProvider>
          <WebSocketProvider>
            <DialogProvider>
              <AppBar />
              {children}
              <Footer />
            </DialogProvider>
          </WebSocketProvider>
        </TickProvider>
      </body>
    </html>
  );
}
