import { Test, TestingModule } from '@nestjs/testing';
import { FiberPrismaRepository } from './fiber.prisma-repository';
import { PrismaService } from '@/shared/infrastructure/services/prisma.service';
import { FiberEntity } from '../../domain/entities/fiber.entity';
import { ResourceStatus } from '@/shared/domain/enums/resource-status.enum';

describe('FiberPrismaRepository (Integration)', () => {
    let repository: FiberPrismaRepository;
    let prisma: PrismaService;

    const testCompanyId = 'c-test-fiber-integration';
    const testZoneId = 'z-test-fiber-integration';
    const testNodeId = 'n-test-fiber-integration';

    beforeAll(async () => {
        const module: TestingModule = await Test.createTestingModule({
            providers: [FiberPrismaRepository, PrismaService],
        }).compile();

        repository = module.get<FiberPrismaRepository>(FiberPrismaRepository);
        prisma = module.get<PrismaService>(PrismaService);

        // Cleanup
        await prisma.fiber.deleteMany({
            where: { nodeId: testNodeId },
        });
        await prisma.node.deleteMany({
            where: { id: testNodeId },
        });
        await prisma.zone.deleteMany({
            where: { id: testZoneId },
        });
        await prisma.company.deleteMany({
            where: { id: testCompanyId },
        });

        // Create prerequisites
        await prisma.company.create({
            data: {
                id: testCompanyId,
                name: 'Test Company Fiber Integration',
            }
        });

        await prisma.zone.create({
            data: {
                id: testZoneId,
                name: 'Test Zone Fiber Integration',
                cidr: '10.0.0.0/16',
                gateway: '10.0.0.1',
                ownerId: testCompanyId,
                createdBy: 'system',
                updatedBy: 'system',
            }
        });

        await prisma.node.create({
            data: {
                id: testNodeId,
                ipAddress: '10.0.0.10',
                status: 'ACTIVE',
                zoneId: testZoneId,
                createdBy: 'system',
                updatedBy: 'system',
            }
        });
    });

    afterAll(async () => {
        await prisma.fiber.deleteMany({
            where: {
                nodeId: testNodeId,
            },
        });
        await prisma.node.deleteMany({
            where: { id: testNodeId },
        });
        await prisma.zone.deleteMany({
            where: { id: testZoneId },
        });
        await prisma.company.deleteMany({
            where: { id: testCompanyId },
        });
        await prisma.$disconnect();
    });

    describe('CRUD Operations', () => {
        let createdFiberId: number;

        it('should create a fiber', async () => {
            const fiber = new FiberEntity(
                'tcp',
                8080,
                ResourceStatus.ACTIVE,
                testNodeId,
                'u-000001',
                {
                    // hostPort will be generated by DB or service, but here repository expects entity to have it if we were passing it,
                    // but FiberEntity constructor doesn't require it.
                }
            );

            const result = await repository.create(fiber);

            expect(result).toBeDefined();
            expect(result.id).toBeDefined();
            expect(result.protocol).toBe('tcp');
            expect(result.targetPort).toBe(8080);
            expect(result.nodeId).toBe(testNodeId);
            createdFiberId = result.id!;
        });

        it('should find a fiber by id', async () => {
            const result = await repository.findById(testZoneId, testNodeId, createdFiberId);

            expect(result).toBeDefined();
            expect(result?.id).toBe(createdFiberId);
            expect(result?.protocol).toBe('tcp');
        });

        it('should find fibers by node id', async () => {
            const result = await repository.findByNodeId(testZoneId, testNodeId);

            expect(result).toBeDefined();
            expect(result.length).toBeGreaterThan(0);
            expect(result.some(f => f.id === createdFiberId)).toBe(true);
        });

        it('should delete a fiber', async () => {
            await repository.delete(testZoneId, testNodeId, createdFiberId);

            const result = await repository.findById(testZoneId, testNodeId, createdFiberId);
            expect(result).toBeNull();
        });
    });
});
