export enum ResourceStatus {
  INACTIVE = 'INACTIVE',
  QUEUED = 'QUEUED',
  PROVISIONING = 'PROVISIONING',
  UPDATING = 'UPDATING',
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
  TERMINATING = 'TERMINATING',
  TERMINATED = 'TERMINATED',
  DELETING = 'DELETING',
  DELETED = 'DELETED',
}