export enum ResourceStatus {
  PROVISIONING = 'PROVISIONING',
  INACTIVE = 'INACTIVE',
  QUEUED = 'QUEUED',
  ACTIVE = 'ACTIVE',
  UPDATING = 'UPDATING',
  FAILED = 'FAILED',
  STOPPING = 'STOPPING',
  DELETING = 'DELETING',
  DELETED = 'DELETED',
}
